swagger: '2.0'
info:
  description: 'This is my prueba tecnica'
  version: '1.0.0'
  title: 'Task Managment'
  contact:
    email: 'garciayohan57@gmail.com'
host: 'localhost:3001'
basePath: '/v2'
tags:
  - name: 'task'
    description: 'Crud para gestionar task'
schemes:
  - 'https'
  - 'http'
paths:
  /api/tasks:
    post:
      tags:
        - 'task'
      summary: 'Create a new task'
      description: ''
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Task object that needs to be added'
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        '400':
          description: Invalid input
      security:
        - api_key: []
    get:
      tags:
        - 'task'
      summary: 'Get all task'
      description: ''
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      responses:
        '400':
          description: Invalid input
        '200':
          description: Task created
      security:
        - api_key: []
  /api/tasks/{id}:
    get:
      tags:
        - 'task'
      summary: 'Get task by id'
      description: ''
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Task id to get'
          required: true
          type: 'string'
      responses:
        '400':
          description: Invalid input
        '401':
          description: Task not found
        '200':
          description: Task found
      security:
        - api_key: []
    put:
      tags:
        - 'task'
      summary: 'Update task by id'
      description: ''
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Task id to update'
          required: true
          type: 'string'
        - in: 'body'
          name: 'body'
          description: 'Task object that needs to be added'
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        '400':
          description: Invalid input
        '401':
          description: Task not found
        '200':
          description: Task modified
      security:
        - api_key: []
    delete:
      tags:
        - 'task'
      summary: 'Delete task by id'
      description: ''
      consumes:
        - 'application/json'
      produces:
        - 'application/json'
      parameters:
        - name: 'id'
          in: 'path'
          description: 'Task id to delete'
          required: true
          type: 'string'
      responses:
        '400':
          description: Invalid input
        '401':
          description: Task not found
        '200':
          description: Task deleted
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: 'apiKey'
    name: 'api_key'
    in: 'header'
definitions:
  Task:
    type: 'object'
    properties:
      title:
        type: 'string'
      description:
        type: 'string'
      status:
        type: 'boolean'
